---
- hosts: webserver
  become: yes
  vars:
      http_port: 80
      doc_dir: /ansible/
      doc_root: /var/www/html/ansible/
      max_clients: 5
      ansible_python_interpreter: python
  tasks:
      - name: ensure httpd installed
        yum: name=httpd state=present
        when: ansible_os_family == "RedHat"
  
      - name: ensure apache running
        service: name=httpd enabled=yes state=started
